
# Create a copy of this file and make sure it's available
# at:  config/metagit.yml


# These email addresses when found in a Git commit history
# will be considered one of your commits
emails:
  - me@example.com
  - me2@example.com

groups:
  - name: My Organisation
    public_meta_repo: git@github.com/username/myorg-meta
    private_repos:
      - path: "/Users/username/code/private1"
      - path: "/Users/username/code/private2"

  - name: Startup
    public_meta_repo: git@github.com/username/startup-meta
    private_repos:
      - path: "/Users/username/code/startup1"
      - path: "/Users/username/code/startup2"
